#!/bin/bash
# Quick startup commands for VISHWAS

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          VISHWAS - Blockchain Criminal Justice System         ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "💡 FOLLOW THESE STEPS:"
echo ""
echo "1️⃣  RESTART DOCKER (if you got registry connection error)"
echo "   └─ Linux:   sudo systemctl restart docker"
echo "   └─ macOS/Windows: Click Docker Desktop → Restart"
echo ""
echo "2️⃣  START VISHWAS"
echo "   └─ ./run.sh"
echo ""
echo "3️⃣  VERIFY IT'S WORKING"
echo "   └─ http://localhost:3000 in your browser"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "❓ IF YOU GET ERRORS:"
echo ""
echo "   Registry connection error? → ./fix-docker-dns.sh"
echo "   Need help? → cat DOCKER_DNS_FIX.md"
echo "   Full guide? → cat DOCKER_FIXES_APPLIED.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION:"
echo ""
echo "   Quick Reference ........... DOCKER_QUICK_REFERENCE.md"
echo "   Setup Guide ............... DOCKER_SETUP_GUIDE.md"
echo "   Production Guide .......... DOCKER_PRODUCTION_GUIDE.md"
echo "   Deployment Status ......... DEPLOYMENT_STATUS.md"
echo "   Documentation Index ....... DOCUMENTATION_INDEX.md"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✨ Ready to go!"
